# Generated by Django 4.1 on 2022-09-15 19:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("tag", models.CharField(max_length=256)),
                ("content", models.TextField()),
                (
                    "create_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022, 9, 15, 19, 53, 9, 294434, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("publish_time", models.DateTimeField(blank=True)),
                ("modify_time", models.DateTimeField(blank=True)),
                ("approve_comments", models.BooleanField(default=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "create_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022, 9, 15, 19, 53, 9, 295785, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "relatedblog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="Blog.blogcontext",
                    ),
                ),
            ],
        ),
    ]
