# Generated by Django 4.1 on 2022-09-16 05:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Blog", "0003_alter_blogcontext_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcontext",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 16, 5, 6, 11, 116981, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 16, 5, 6, 11, 117934, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="UserProfileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(blank=True, upload_to="basic_app/profile_pics"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
