# Generated by Django 4.1 on 2022-09-16 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0004_alter_blogcontext_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcontext",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 16, 5, 6, 15, 797864, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 16, 5, 6, 15, 798840, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
