# Generated by Django 4.1 on 2022-09-16 22:27

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0007_alter_blogcontext_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcontext",
            name="create_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="comments",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 16, 22, 27, 12, 339927, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
