# Generated by Django 4.1 on 2022-09-16 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0009_alter_comments_create_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 16, 22, 31, 8, 356082, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
