# Generated by Django 4.1 on 2022-09-16 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0010_alter_comments_create_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="create_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
