# Generated by Django 4.1 on 2022-09-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0012_alter_blogcontext_publish_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcontext",
            name="modify_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
