# Generated by Django 4.1 on 2022-09-16 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0013_alter_blogcontext_modify_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofileinfo",
            name="create_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
